resources:
  repositories:
    - repository: YamlTemplates
      type: git
      name: YamlTemplates/YamlTemplates
      ref: main

trigger:
  branches:
    include:
      - develop

variables:
  - name: DockerServiceConnection
    value: 'sc-tey-acr-np-002'
  - name: tag
    value: $(Build.BuildId)
  - name: AppServiceConnectionName
    value: 'sc-tey-nonprod-001'

stages:
  - stage: BuildQA
    variables:
      - group: QA_TeyaseerApp
      - group: QA_ENV_TeyaseerApp
      - group: Google-maps-API-key-group
    jobs:
      - template: /Build/BuildAndPushDockerImageDiffAgent.yml@YamlTemplates
        parameters:
          DockerServiceConnection: 'sc-tey-acr-np-002'
          build_args: '--build-arg NEXT_PUBLIC_CONTENTFUL_SPACE_ID=$(NEXT_PUBLIC_CONTENTFUL_SPACE_ID) --build-arg NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=$(NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN) --build-arg NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=$(NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT) --build-arg NEXT_PUBLIC_MAPS_API_KEY=$(NEXT_PUBLIC_MAPS_API_KEY) --build-arg NEXT_PUBLIC_USERS_API_BASE_URL=$(NEXT_PUBLIC_USERS_API_BASE_URL) --build-arg NEXT_PUBLIC_VENDORS_API_BASE_URL=$(NEXT_PUBLIC_VENDORS_API_BASE_URL) --build-arg NEXT_PUBLIC_COST_CALCULATOR_API_BASE_URL=$(NEXT_PUBLIC_COST_CALCULATOR_API_BASE_URL) --build-arg NEXT_PUBLIC_BASE_URL=$(NEXT_PUBLIC_BASE_URL) --build-arg NEXT_PUBLIC_FORGEROCK_AM_URL=$(NEXT_PUBLIC_FORGEROCK_AM_URL) --build-arg NEXT_PUBLIC_CALENDLY_BASE_URL=$(NEXT_PUBLIC_CALENDLY_BASE_URL)  --build-arg NEXT_PUBLIC_REVALIDATION_TOKEN=$(NEXT_PUBLIC_REVALIDATION_TOKEN) --build-arg NEXT_PUBLIC_SOURCE_VERSION=$(tag) --build-arg NEXT_PUBLIC_GA_ID=$(NEXT_PUBLIC_GA_ID) --build-arg NEXT_PUBLIC_ONLY_UAT_FEATURES_ENABLED=$(NEXT_PUBLIC_ONLY_UAT_FEATURES_ENABLED) --build-arg NEXT_UAE_PASS_LOGOUT_URL=$(NEXT_UAE_PASS_LOGOUT_URL) --build-arg NEXT_PUBLIC_FORGEROCK_OAUTH_CLIENT=$(NEXT_PUBLIC_FORGEROCK_OAUTH_CLIENT) --build-arg NEXT_PUBLIC_DATADOG_APP_ID=$(NEXT_PUBLIC_DATADOG_APP_ID) --build-arg NEXT_PUBLIC_DATADOG_CLIENT_TOKEN=$(NEXT_PUBLIC_DATADOG_CLIENT_TOKEN) --build-arg NEXT_PUBLIC_DATADOG_SITE=$(NEXT_PUBLIC_DATADOG_SITE) --build-arg NEXT_PUBLIC_DATADOG_SERVICE=$(NEXT_PUBLIC_DATADOG_SERVICE) --build-arg NEXT_PUBLIC_DATADOG_ENV=$(NEXT_PUBLIC_DATADOG_ENV) --build-arg NEXT_PUBLIC_DATADOG_VERSION=$(NEXT_PUBLIC_DATADOG_VERSION) --build-arg NEXT_PUBLIC_DATADOG_ALLOWTRACINGURL=$(NEXT_PUBLIC_DATADOG_ALLOWTRACINGURL) --build-arg NEXT_PUBLIC_DATADOG_TRACKUSERINTERACTIONS=$(NEXT_PUBLIC_DATADOG_TRACKUSERINTERACTIONS) --build-arg NEXT_PUBLIC_DATADOG_TRACKRESOURCES=$(NEXT_PUBLIC_DATADOG_TRACKRESOURCES) --build-arg NEXT_PUBLIC_DATADOG_TRACKLONGTASKS=$(NEXT_PUBLIC_DATADOG_TRACKLONGTASKS) --build-arg NEXT_PUBLIC_DATADOG_FORWARDERRORSTOLOGS=$(NEXT_PUBLIC_DATADOG_FORWARDERRORSTOLOGS)'


  - stage: QA
    dependsOn: BuildQA
    displayName: Deploying to QA environment
    pool:
      name: Tey-nonprod
    variables:
      - group: QA_TeyaseerApp
      - group: QA_ENV_TeyaseerApp
      - group: Google-maps-API-key-group

    jobs:
      - template: /Release/AppServiceContainer.yml@YamlTemplates
        parameters:
          Environment: 'QA_TeyaseerApp'
