# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  - develop
pr:
  - develop

resources:
  - repo: self

variables:
  - name: tag
    value: '$(Build.SourceBranchName)-$(Build.BuildId)'
  - name: imageRepository
    value: 'teyaseer.web.develop'
  - group: QA_TeyaseerApp
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: npmAuthenticate@0
            inputs:
              workingFile: '.npmrc'
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: 'amadkormonstarlab-ACR'
              repository: '$(imageRepository)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: '$(tag)'
              arguments: '--build-arg NEXT_PUBLIC_CONTENTFUL_SPACE_ID=$(NEXT_PUBLIC_CONTENTFUL_SPACE_ID) --build-arg NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=$(NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN) --build-arg NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=$(NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT) --build-arg NEXT_PUBLIC_MAPS_API_KEY=$(NEXT_PUBLIC_MAPS_API_KEY) --build-arg NEXT_PUBLIC_USERS_API_BASE_URL=$(NEXT_PUBLIC_USERS_API_BASE_URL) --build-arg NEXT_PUBLIC_VENDORS_API_BASE_URL=$(NEXT_PUBLIC_VENDORS_API_BASE_URL) --build-arg NEXT_PUBLIC_COST_CALCULATOR_API_BASE_URL=$(NEXT_PUBLIC_COST_CALCULATOR_API_BASE_URL) --build-arg NEXT_PUBLIC_BASE_URL=$(NEXT_PUBLIC_BASE_URL) --build-arg NEXT_PUBLIC_FORGEROCK_AM_URL=$(NEXT_PUBLIC_FORGEROCK_AM_URL) --build-arg NEXT_PUBLIC_CALENDLY_BASE_URL=$(NEXT_PUBLIC_CALENDLY_BASE_URL)  --build-arg NEXT_PUBLIC_REVALIDATION_TOKEN=$(NEXT_PUBLIC_REVALIDATION_TOKEN) --build-arg NEXT_PUBLIC_SOURCE_VERSION=$(tag) --build-arg NEXT_PUBLIC_GA_ID=$(NEXT_PUBLIC_GA_ID) --build-arg NEXT_PUBLIC_ONLY_UAT_FEATURES_ENABLED=$(NEXT_PUBLIC_ONLY_UAT_FEATURES_ENABLED) --build-arg NEXT_UAE_PASS_LOGOUT_URL=$(NEXT_UAE_PASS_LOGOUT_URL) --build-arg NEXT_PUBLIC_FORGEROCK_OAUTH_CLIENT=$(NEXT_PUBLIC_FORGEROCK_OAUTH_CLIENT)'
